---
- name: restore playbook.yml
  hosts: all
  tasks: 
    # 1) /etc/ansible/facts.d 디렉토리 삭제
    - name: 1) /etc/ansible/facts.d 디렉토리 삭제
      file:
        path: /etc/ansible/facts.d
        state: absent

    # 2) 웹 서비스 중지 - httpd
    - name: 2) 웹 서비스 중지 - httpd
      service:
        name: httpd
        state: stopped
        enabled: no
      ignore_errors: yes

    # 3) 웹 패키지 삭제 - httpd
    - name: 3) 웹 패키지 삭제 - httpd
      yum:
        name: httpd
        state: absent