---
# tasks file for myfirewall
# 1) 패키지 설치 - firewalld
- name: 패키지 설치 - firewalld
  yum: 
    name: firewalld
    state: latest

# 2) 서비스 기동 - firewalld
- name: 서비스 기동 - firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

# 3) 방화벽 서비스 등록 - http
- name: 방화벽 서비스 등록 - {{ firewall_service }}
  firewalld:
    service: "{{ firewall_service }}"
    permanent: yes
    immediate: yes
    state: enabled

