---
- name: 사용자 정의 팩트 배포
  hosts: web1
  vars:
    remot_dir: /etc/ansible/facts.d
    facts_file: files/custom.fact
  tasks: 
    # 1) 디렉토리 생성 - /etc/ansible/fact.d
    - name: 1) 디렉토리 생성 - /etc/ansible/facts.d
      file:
        path: "{{ remot_dir }}"
        state: directory
        mode: '0755'

    # 2) 팩트 파일 배포
    - name: 2) 팩트 파일 배포
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remot_dir }}"
