---
# 웹 패키지 설치 및 기동
# 1) 패키지 설치 - httpd, mod_ssl
- name: 패키지 설치 - {{ pkg_webs }}
  yum:
    name: "{{ pkg_webs }}"
    state: latest

# 2) 서비스 기동 - httpd
- name: 서비스 기동 - {{ svc_web }}
  service:
    name: "{{ svc_web }}"
    state: started
    enabled: yes