---
- name: fileserver 패키지 설치
  hosts: fileservers
  tasks:
    - name: vars 추가
      include_vars: package.yml

    - name: tasks 추가
      include_tasks: install_package.yml
      vars:
        packages:
          web_pkg: epel-release

    - name: task 추가 2
      include_tasks: install_package.yml
      vars:
        packages:
          web_pkg: tomcat