---
- name: restore playbook.yml
  hosts: all
  vars_files:
    - paths.yml
  tasks: 
    # 1) 디렉토리 2개 삭제 - paths.yml 
    - name: 1) 디렉토리 2개 삭제 - paths.yml
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ paths.fileserver }}"
        - "{{ paths.dbpath }}"

    # 2) 패키지 2개 삭제 - httpd, tomcat
    - name: 2) 패키지 2개 삭제 - httpd, tomcat
      yum:
        name: 
          - httpd
          - tomcat
        state: absent