---
- name: restore the site.yml
  hosts: webservers
  tasks: 
    # 1) 방화벽 (firewall-cmd --permanent --remove-service={http,https})
    - name: (1) 방화벽 서비스 내리기 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - http
        - https

    # 2) 서비스 중지(systemctl disable --now httpd)
    - name: (2) 웹서비스 내리기 - httpd
      service:
        name: httpd
        state: stopped
        enabled: no

    # 3) index 파일 삭제(/var/www/html/index.html 삭제)
    - name: (3) /var/www/html/index.html 파일 지우기
      file:
        path: /var/www/html/index.html
        state: absent

    # 4) 패키지 삭제(yum -y remove httpd mod_ssl)
    - name: (4) 패키지 삭제 - httpd, mod_ssl
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - httpd
        - mod_ssl
