---
- name: Restore web-db.yml
  hosts: all
  tasks: 
    # (1) 방화벽 내리기 - http, https
    - name: (1) 방화벽 내리기 - http, https)
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - http
        - https
      ignore_errors: yes

    # (2) 웹서비스 설정 삭제 - /var/www/html/index.php
    - name: (2) 웹서비스 설정 삭제 - /var/www/html/index.php
      file:
        path: /var/www/html/index.php
        state: absent

    # (3) 서비스 중지 - httpd, mariadb
    - name: (3) 서비스 중지 - httpd, mariadb
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - httpd
        - mariadb
      ignore_errors: yes
      
    # (4) 패키지 삭제 - WEB(httpd, mod_ssl, php, php-mysqlnd, php-pdo), DB(mariadb), firewall(firewalld)
    - name: (4) 패키지 삭제 - WEB(httpd, mod_ssl, php, php-mysqlnd, php-pdo), DB(mariadb), firewall(firewalld)
      yum:
        name:
          - httpd
          - mod_ssl
          - php
          - php-mysqlnd
          - php-pdo
          - mariadb-server
          - firewalld 
        state: absent