---
- name: Task Failure Exercise
  hosts: databases
  gather_facts: no
  vars:
    web_package: httpd     # 잘못된 정보 그대로 입력
    db_package: mariadb-server
    db_servcie: mariadb
  tasks:
    - name: Check local time
      command: /usr/bin/date
      register: command_result
      changed_when: false

    - name: Print local time
      debug:
        var: command_result.stdout

    - name: block ~ rescue ~ always
      block:
      - name: Install {{ web_package }} package
        yum:
          name: "{{ web_package }}"
          state: present 
        failed_when: web_package == "httpd"
      rescue:
      - name: Install {{ db_package }} package
        yum:
          name: "{{ db_package }}"
          state: present
      always:
      - name: start {{ db_servcie }} db_servcie
        service:
          name: "{{ db_servcie }}"
          state: started
          enabled: yes