---
- name: 로그 수집 작업
  hosts: all
  tasks:
    - name: 파일 모으기 - /var/log/secure
      fetch:
        src: /var/log/secure
        dest: secure-backups/{{ inventory_hostname }}-securelog
        flat: yes
