---
- name: 1st play
  hosts: web1
  tasks: 
    - name: 패키지 설치 - httpd, mod_ssl, firewalld
      yum:
        name: 
          - httpd
          - mod_ssl
          - firewalld
        state: latest

    - name: 웹서비스 설정 - /var/www/html/index.html
      copy:
        content: "Welcome To My Server \n"
        dest: /var/www/html/index.html

    - name: 서비스 기동 -httpd, firewalld
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld

    - name: 방화벽 등록 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https


- name: 2nd play
  hosts: localhost
  tasks: 
    - name: Test the Web page
      uri:
        url: http://web1.example.com
        return_content: yes
        status_code: 200