---
- name: MAIL서버 작업
  hosts: all
  gather_facts: yes
  tasks: 
    - name: Include configure_main.yml
      include: configure_mail.yml
      when: inventory_hostname in groups['mailservers']
  
  handlers:
    - name: start_postfix
      service:
        name: postfix
        state: started
    
    - name: start_dovecot
      service:
        name: dovecot
        state: started
    
    - name: restart_postfix
      service:
        name: postfix
        state: restarted