---
- name: motd 배포
  hosts: all
  gather_facts: yes
  vars:
    system_owner: webmaster@example.com
  tasks: 
    - name: /etc/motd 파일 배포
      template:
        src: template/motd.j2
        dest: /etc/motd

        